Class User.d Extends %Persistent
{
/// Dave
Storage Default
{
<Data name="dDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^User.dD</DataLocation>
<DefaultData>dDefaultData</DefaultData>
<Description>
<![CDATA[Dave]]></Description>
<IdLocation>^User.dD</IdLocation>
<IndexLocation>^User.dI</IndexLocation>
<StreamLocation>^User.dS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
